ipynb-filters: [nbdev_filter]

project:
  type: website
  output-dir: docs
  preview:
    port: 3000
    browser: false

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

website:
  title: "ghapi"
  description: "A python client for the GitHub API"
  twitter-card: true
  open-graph: true
  reader-mode: true
  repo-branch: master
  repo-url: https://github.com/fastai/ghapi/tree/master/
  repo-actions: [issue]
  navbar:
    background: primary
    search: true
    right:
      - icon: github
        href: https://github.com/fastai/ghapi/tree/master/
  sidebar:
    style: "floating"

metadata-files: 
  - sidebar.yml
  - custom.yml
