"""Docs: https://ghapi.fast.ai/build_lib.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/90_build_lib.ipynb.

# %% auto #0
__all__ = ['GH_OPENAPI_URL', 'build_spec', 'build_gql_spec']

# %% ../nbs/90_build_lib.ipynb #cdbcf258
from fastcore.all import *
from fastspec.spec import SpecParser
from fastspec.gql import GqlSpec, INTROSPECT

import json, httpx

# %% ../nbs/90_build_lib.ipynb #c215ed8d
GH_OPENAPI_URL = 'https://github.com/github/rest-api-description/raw/main/descriptions/api.github.com/api.github.com.json?raw=true' 

# %% ../nbs/90_build_lib.ipynb #cf7204d9
def build_spec(nm='ghapi/gh_spec.py', url=GH_OPENAPI_URL):
    "Regenerate the compact spec module `gh_spec.py` from GitHub's OpenAPI description."
    SpecParser.from_openapi(dict2obj(json.loads(urlread(url)))).save(nm)

# %% ../nbs/90_build_lib.ipynb #9aef0afb
def build_gql_spec(nm='ghapi/gql_spec.py', url='https://api.github.com/graphql'):
    "Regenerate the distilled GraphQL schema tables shipped as `ghapi.gql_spec`."
    r = httpx.post(url, json=dict(query=INTROSPECT), headers=dict(Authorization=f'bearer {os.environ["GITHUB_TOKEN"]}'), timeout=60)
    r.raise_for_status()
    GqlSpec.from_introspection(r.json()).save(nm)
