"""Query GitHub's GraphQL API: schema-aware chained queries, one-request batching, and raw GraphQL

GitHub's REST API returns each resource's fixed shape, so a read that fans out -- "the head commit of these 100 repos" -- is 100 round trips, most of whose bytes you discard. The GraphQL API is one endpoint that accepts a *shape*: describe the nesting you want and the server returns exactly that, in one round trip. `GhGql` is [fastspec's GraphQL client](https://answerdotai.github.io/fastspec/gql.html) bound to GitHub: the schema ships pre-distilled with this package, so discovery (`xdir`, attribute completion, rich reprs), schema-checked query chaining with plain-kwargs arguments, and one-request batching all work with no setup beyond a `GITHUB_TOKEN`. Raw GraphQL text works at every level, and only query fields are exposed as attributes -- mutations require deliberately writing raw text.

`GhGql` is a thin binding: fastspec's `GqlClient` pointed at GitHub's endpoint, authenticated from `GITHUB_TOKEN` (or an explicit `token=`), with the shipped schema loaded. Fragments, `batch`, `gql.t`, raw calls, and `GqlError` with partial data are all inherited.

Because a query is a shape, "run these N fragments" is just one bigger shape: `batch` aliases each fragment into a single request and returns results in input order. Checking which of a hundred repos moved -- the `ws-sync` fast path that motivated this module -- is one round trip.

Not everything sits on a path you are building: enum values, input-object shapes, and union membership are looked up rather than navigated to. `gql.t` indexes every schema type by name.

Docs: https://ghapi.fast.ai/graphql.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/05_graphql.ipynb.

# %% auto #0
__all__ = ['GQL_URL', 'GhGql', 'GqlError']

# %% ../nbs/05_graphql.ipynb #f18b651e
from fastcore.utils import *
from fastspec.gql import GqlSpec, GqlClient, GqlError  # chkstyle: ignore

# %% ../nbs/05_graphql.ipynb #b44eb8a0
_all_ = ['GqlError']

# %% ../nbs/05_graphql.ipynb #76276138
GQL_URL = 'https://api.github.com/graphql'

class GhGql(GqlClient):
    "GitHub GraphQL client using the shipped distilled schema"
    def __init__(self, token=None):
        from ghapi.gql_spec import gqlspec
        super().__init__(GqlSpec.from_dict(gqlspec), GQL_URL,
            headers={'Authorization': f'bearer {token or os.environ["GITHUB_TOKEN"]}'})
