"""Query GitHub's GraphQL API with schema-aware chaining, batched requests and raw GraphQL

GitHub's GraphQL API lets you request specific fields from several resources in one query. For example, you can fetch the head commits of many repositories without a separate REST request for each repository.

`GhGql` uses [fastspec's GraphQL client](https://answerdotai.github.io/fastspec/gql.html) with GitHub's schema. Set `GITHUB_TOKEN` to get started. Explore fields with `xdir`, attribute completion and rich displays. Build query fragments by chaining attributes and passing keyword arguments. The client checks field names against the bundled schema.

You can also use raw GraphQL for complete queries or selections within a field. Attributes expose query fields. Mutations require raw GraphQL text.

`GhGql` configures `GqlClient` with GitHub's endpoint and the bundled schema. Authentication uses `GITHUB_TOKEN` or an explicit `token=`. It inherits fragments, `batch`, `gql.t` and raw queries. `GqlError` retains the server's errors and any partial data.

`batch` accepts query fragments as separate arguments or one iterable. Results keep the input order. `repo` builds a repository fragment from an `'owner/name'` string.

`GhGql` sends batches of up to 25 fragments concurrently. GitHub resolves aliases within each query serially. In a measurement with 103 repositories, one query took 5.5 seconds and chunked requests took 1.7 seconds.

Fetch the repositories' head commits in one `batch` call:

Use `gql.t` to look up schema types by name. It shows enum values, input-object fields and union members:

Docs: https://ghapi.fast.ai/graphql.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/05_graphql.ipynb.

# %% auto #0
__all__ = ['GQL_URL', 'GhGql', 'GqlError']

# %% ../nbs/05_graphql.ipynb #f18b651e
from fastcore.utils import *
from fastspec.gql import GqlSpec, GqlClient, GqlError

# %% ../nbs/05_graphql.ipynb #b44eb8a0
_all_ = ['GqlError']

# %% ../nbs/05_graphql.ipynb #76276138
GQL_URL = 'https://api.github.com/graphql'

class GhGql(GqlClient):
    "GitHub GraphQL client using the shipped distilled schema"
    batch_chunk = 25  # GitHub resolves aliases serially, so large batches go as parallel chunked requests
    def __init__(self, token=None):
        from ghapi.gql_spec import gqlspec
        super().__init__(GqlSpec.from_dict(gqlspec), GQL_URL,
            headers={'Authorization': f'bearer {token or os.environ["GITHUB_TOKEN"]}'})

    def repo(self, spec):
        "Repository fragment for an `'owner/name'` spec"
        o, n = spec.split('/')
        return self.repository(owner=o, name=n)
