"""Parallel and serial pagination

Docs: https://ghapi.fast.ai/page.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/03_page.ipynb.

# %% auto #0
__all__ = ['paged', 'parse_link_hdr', 'pages', 'sync_paged', 'sync_pages', 'NotifRow', 'NotifRows', 'gh_notifs']

# %% ../nbs/03_page.ipynb #6a0bf465
from fastcore.all import *
from .core import *
from .core import _age
from fasttransport.errors import APIError

import re, asyncio
from datetime import datetime, timedelta, timezone
from urllib.parse import parse_qs,urlsplit

# %% ../nbs/03_page.ipynb #cea42302
async def paged(oper, *args, per_page=30, max_pages=9999, **kwargs):
    "Convert operation `oper(*args,**kwargs)` into an async iterator, requesting pages serially until one comes back empty"
    for i in range(1, max_pages+1):
        res = await oper(*args, per_page=per_page, page=i, **kwargs)
        if not res: return
        yield res

# %% ../nbs/03_page.ipynb #56bd053b
class _Scanner:
    def __init__(self, buf): self.buf,self.match = buf,None
    def __getitem__(self, key): return self.match.group(key)
    def scan(self, pattern):
        self.match = re.compile(pattern).match(self.buf)
        if self.match: self.buf = self.buf[self.match.end():]
        return self.match

_QUOTED        = r'"((?:[^"\\]|\\.)*)"'
_TOKEN         = r'([^()<>@,;:\"\[\]?={}\s]+)'
_RE_COMMA_HREF = r' *,? *< *([^>]*) *> *'
_RE_ATTR       = rf'{_TOKEN} *(?:= *({_TOKEN}|{_QUOTED}))? *'

# %% ../nbs/03_page.ipynb #c8de1f90
def _parse_link_hdr(header):
    "Parse an RFC 5988 link header, returning a `list` of `tuple`s of URL and attr `dict`"
    scanner,links = _Scanner(header),[]
    while scanner.scan(_RE_COMMA_HREF):
        href,attrs = scanner[1],[]
        while scanner.scan('; *'):
            if scanner.scan(_RE_ATTR):
                attr_name, token, quoted = scanner[1], scanner[3], scanner[4]
                if quoted is not None: attrs.append([attr_name, quoted.replace(r'\"', '"')])
                elif token is not None: attrs.append([attr_name, token])
                else: attrs.append([attr_name, None])
        links.append((href,dict(attrs)))
    if scanner.buf: raise Exception(f"parse() failed at {scanner.buf!r}")
    return links

# %% ../nbs/03_page.ipynb #5af9f0d7
def parse_link_hdr(header):
    "Parse an RFC 5988 link header, returning a `dict` from rels to a `tuple` of URL and attrs `dict`"
    return {a.pop('rel'):(u,a) for u,a in _parse_link_hdr(header)}

# %% ../nbs/03_page.ipynb #581beb00
@patch
def last_page(self:GhApi):
    "Parse RFC 5988 link header from most recent operation, and extract the last page"
    header = self.recv_hdrs.get('Link', '')
    last = nested_idx(parse_link_hdr(header), 'last', 0) or ''
    qs = parse_qs(urlsplit(last).query)
    return int(nested_idx(qs,'page',0) or 0)

# %% ../nbs/03_page.ipynb #75052160
async def pages(oper, n_pages, *args, per_page=100, **kwargs):
    "Get `n_pages` pages from `oper(*args,**kwargs)`, in parallel"
    return L(await asyncio.gather(*[oper(*args, per_page=per_page, page=i, **kwargs) for i in range(1,n_pages+1)]))

# %% ../nbs/03_page.ipynb #700bc21c
def sync_paged(oper, *args, per_page=30, max_pages=9999, **kwargs):
    "`paged` for a `sync=True` client: request pages serially until one comes back empty"
    for i in range(max_pages):
        res = oper(*args, per_page=per_page, page=i+1, **kwargs)
        if not res: return
        yield res

# %% ../nbs/03_page.ipynb #2744ab66
def sync_pages(oper, n_pages, *args, per_page=100, n_workers=16, **kwargs):
    "Get `n_pages` pages from `oper(*args,**kwargs)` on a `sync=True` client, in parallel via threads"
    return L(parallel(lambda i: oper(*args, per_page=per_page, page=i+1, **kwargs),
        range(n_pages), threadpool=True, n_workers=n_workers))

# %% ../nbs/03_page.ipynb #58141083
class NotifRow(AttrDict):
    "One notification thread as an actionable line"
    def __repr__(self):
        s = self.subject
        num = s.url.rpartition('/')[2] if s.url else ''
        kind = ('PR' if s.type=='PullRequest' else s.type) + (f' #{num}' if num.isdigit() else '')
        return f'{self.id}  {_age(self.updated_at)}  {self.reason}  {self.repository.full_name}  {self.get("mark","")}{kind}: {s.title}'

class NotifRows(GhRows):
    "Notification rows; displays 'no notifications' when empty"
    def __repr__(self): return super().__repr__() or 'no notifications'

def _notif_mark(sub):
    "`[merged] `/`[closed] ` marker for a fetched subject; empty for open or unfetchable subjects"
    if not sub: return ''
    if sub.get('merged_at'): return '[merged] '
    if sub.get('state') == 'closed': return '[closed] '
    return ''

async def gh_notifs(days=5, reasons=('mention', 'review_requested', 'author', 'assign'), include_read=False, per_page=100):
    "Notifications from the past `days` (all available if None) as `NotifRows`, marked `[closed]`/`[merged]` when the subject is no longer open; `reasons=None` includes every reason"
    api = GhApi()
    since = (datetime.now(timezone.utc) - timedelta(days=days)).isoformat() if days else None
    notifs = L([o async for o in paged(api.activity.list_notifications_for_authenticated_user, all=include_read, since=since, per_page=per_page)]).concat()
    if reasons: notifs = notifs.filter(lambda n: n.reason in reasons)
    async def _get(u):
        if not u: return None
        try: return await api(u, 'GET')
        except APIError: return None   # deleted or inaccessible subjects lose their mark, not the whole listing
    subs = await asyncio.gather(*(_get(n.subject.url) for n in notifs))
    for n, s in zip(notifs, subs): n['mark'] = _notif_mark(s)
    return NotifRows(NotifRow(o) for o in notifs)

# %% ../nbs/03_page.ipynb #abc91f9e
@patch
async def mark_done(self:GhApi, *ids):
    "Mark notification threads as done, removing them from the inbox (the API cannot list done threads back)"
    await asyncio.gather(*(self.activity.mark_thread_as_done(i) for i in ids))
