name: test
on:
  workflow_dispatch:
defaults:
  run: { shell: bash }

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v2
      with: {python-version: '3.8'}
    - name: Run script
      env:
        CONTEXT_GITHUB: ${{ toJson(github) }}
        TESTING: |
          abc
          def
          gh"i"
      run: |
        echo a
        echo "$TESTING"
        echo b
        pip install -q ghapi
        python .github/scripts/build-test.py

